### ISSUE TITLE
Simple Form Helpers, bootstrap integration?

### ISSUE THREAD

**Issue by rbosch** [code-and-effect/effective_resources#4]
Hi,

Wouldn't call it a bug, but not sure how to reach you. Giving this a shot.

According to the docs, you can use 
```
simple_form_for( ..) do |f|
      f.input  :name
```
Anyway to set the classes for the group, label and fields to bootstrap classes?

Another question is the buttons rendered below.

with 
`= simple_form_submit(f)`

I'm getting 3 buttons, Save, Continue, Add new. But there is rendered a another Continue button below. See screenshot. 

Where can i change the layout of these buttons?

![screen shot 2018-01-11 at 10 48 42](https://user-images.githubusercontent.com/1810029/34819156-4c23160a-f6bd-11e7-969a-924658cfef19.png)

**Comment by rbosch** [comment]
Sorry, your simple_form addresses, I think, the simple_form gem, that was not immediate clear. Maybe update the readme.

**Comment by matt-riemer** [comment]
Hey @rbosch !

Yep, my toolchain includes [simple_form](https://github.com/plataformatec/simple_form) which is a popular rails form gem.

I use it over the built in rails helpers, or formtastic, because it CAN be configured to output bootstrap3 forms, with html markup exactly matching:

https://getbootstrap.com/docs/3.3/css/#forms

To get the simple_form to do the right thing, you gotta install it with bootstrap3 options:

https://github.com/plataformatec/simple_form#bootstrap

I also have an example of my config/initializer file that might be a good reference:

https://github.com/code-and-effect/effective_style_guide/blob/master/lib/generators/effective_style_guide/simple_form_bootstrap3.rb

^ I kind of just copy that file from project to project and it does the right thing with bootstrap forms.

You might also check out effective_form_inputs gem if you want some better form inputs that forsure work with simple_form and bootstrap3 :)

Cheers,

**Comment by rbosch** [comment]
@matt-riemer awesome, thanks!
